version: '3.7'

services:
  spark-master:
    image: image_bitnami
    container_name: master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 172.24.0.2
    volumes:
      - ./file.py:/opt/bitnami/spark/file.py  

  spark-node-1:
    image: image_bitnami
    container_name: node1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://172.24.0.2:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-node-2:
    image: image_bitnami
    container_name: node2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://172.24.0.2:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-submit:
    image: image_bitnami
    container_name: submitter
    depends_on:
      - spark-master
    command: spark-submit --master spark://172.24.0.2:7077 /opt/bitnami/spark/file.py
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24

